class EsmaEntry {
  final String arabic;
  final String turkish;
  final String meaning;
  final int value;
  final int zikirCount;
  final String fazilet;
  final String nefsMertebesi;

  const EsmaEntry({
    required this.arabic,
    required this.turkish,
    required this.meaning,
    required this.value,
    required this.zikirCount,
    required this.fazilet,
    required this.nefsMertebesi,
  });
}

const List<EsmaEntry> esmaList = [
  EsmaEntry(
      arabic: 'الله',
      turkish: 'Allah',
      meaning: 'Yüce Allah — Varlığı zorunlu, mutlak ilah',
      value: 66,
      zikirCount: 100,
      fazilet: 'Her zaman oku, kalp huzurunu bulur',
      nefsMertebesi: 'Kâmile'),
  EsmaEntry(
      arabic: 'الرحمن',
      turkish: 'Er-Rahman',
      meaning: 'Çok merhametli — Dünya ve ahirette tüm varlıklara rahmet eden',
      value: 298,
      zikirCount: 100,
      fazilet: 'Kalp katılığını giderir, merhamet kapılarını açar',
      nefsMertebesi: 'Mutmainne'),
  EsmaEntry(
      arabic: 'الرحيم',
      turkish: 'Er-Rahim',
      meaning: 'Pek merhametli — Ahirette müminlere özel sonsuz rahmet',
      value: 258,
      zikirCount: 100,
      fazilet: 'Sevgiye kavuşturur, günahlara af kapısı açar',
      nefsMertebesi: 'Mutmainne'),
  EsmaEntry(
      arabic: 'الملك',
      turkish: 'El-Melik',
      meaning: 'Mutlak hükümdar — Her şeyin gerçek sahibi ve yöneticisi',
      value: 90,
      zikirCount: 121,
      fazilet: 'Sabah 121 kez oku, kalpte zenginlik hissi artar',
      nefsMertebesi: 'Radiyye'),
  EsmaEntry(
      arabic: 'القدوس',
      turkish: 'El-Kuddüs',
      meaning: 'Her türlü noksanlıktan münezzeh — Sonsuz temiz ve pak',
      value: 170,
      zikirCount: 100,
      fazilet: 'Kalbi temizler, günahlardan arındırır',
      nefsMertebesi: 'Levvame'),
  EsmaEntry(
      arabic: 'السلام',
      turkish: 'Es-Selam',
      meaning: 'Esenlik kaynağı — Her çeşit kusurdan salim olan',
      value: 131,
      zikirCount: 160,
      fazilet: 'Hastalara 160 kez oku, şifa verir; huzur getirir',
      nefsMertebesi: 'Mutmainne'),
  EsmaEntry(
      arabic: 'المؤمن',
      turkish: 'El-Mümin',
      meaning: 'Güven veren — Kullarını emniyete alan',
      value: 136,
      zikirCount: 136,
      fazilet: 'Korkuyu giderir, emniyeti artırır',
      nefsMertebesi: 'Mülhime'),
  EsmaEntry(
      arabic: 'المهيمن',
      turkish: 'El-Müheymin',
      meaning: 'Gözetip koruyan — Her şeyi kontrol ve muhafaza eden',
      value: 145,
      zikirCount: 100,
      fazilet: 'Manevi ilerleme için okurken gözetileceğini hissedersin',
      nefsMertebesi: 'Mülhime'),
  EsmaEntry(
      arabic: 'العزيز',
      turkish: 'El-Aziz',
      meaning: 'Mutlak güç sahibi — Yenilmez ve üstün olan',
      value: 94,
      zikirCount: 40,
      fazilet: 'Güç kazandırır, zilleti giderir',
      nefsMertebesi: 'Emmare'),
  EsmaEntry(
      arabic: 'الجبار',
      turkish: 'El-Cebbar',
      meaning:
          'Zorla yaptıran, onarıcı — Her şeyi kendi iradesine boyun eğdiren',
      value: 206,
      zikirCount: 206,
      fazilet: 'Kırık kalpleri onarır, zulme karşı korur',
      nefsMertebesi: 'Levvame'),
  EsmaEntry(
      arabic: 'المتكبر',
      turkish: 'El-Mütekebbir',
      meaning: 'Kibriyaya layık tek varlık — Büyüklük yalnız ona aittir',
      value: 662,
      zikirCount: 100,
      fazilet: 'Kibri kırar, tevazuyu artırır',
      nefsMertebesi: 'Levvame'),
  EsmaEntry(
      arabic: 'الخالق',
      turkish: 'El-Halik',
      meaning: 'Yaratan — Yoktan var eden',
      value: 731,
      zikirCount: 100,
      fazilet: 'Yaratıcılığı artırır, yeni kapılar açar',
      nefsMertebesi: 'Mülhime'),
  EsmaEntry(
      arabic: 'البارئ',
      turkish: 'El-Bari',
      meaning: 'Şekil veren — Kusursuz biçim veren',
      value: 213,
      zikirCount: 100,
      fazilet: 'Hastalıklardan korunmak için okunur',
      nefsMertebesi: 'Mülhime'),
  EsmaEntry(
      arabic: 'المصور',
      turkish: 'El-Musavvir',
      meaning: 'Suret veren — Dilediği şekilde biçim veren',
      value: 336,
      zikirCount: 336,
      fazilet: 'Güzelliği artırır, sanatsal yeteneklere destek olur',
      nefsMertebesi: 'Mülhime'),
  EsmaEntry(
      arabic: 'الغفار',
      turkish: 'El-Gaffar',
      meaning: 'Çok bağışlayan — Tekrar tekrar affeden',
      value: 1281,
      zikirCount: 100,
      fazilet: 'Günahların bağışlanması için okunur',
      nefsMertebesi: 'Levvame'),
  EsmaEntry(
      arabic: 'القهار',
      turkish: 'El-Kahhar',
      meaning: 'Her şeye galip — Baskı ve zorla boyun eğdiren',
      value: 306,
      zikirCount: 100,
      fazilet: 'Nefis mücadelesinde güç verir',
      nefsMertebesi: 'Emmare'),
  EsmaEntry(
      arabic: 'الوهاب',
      turkish: 'El-Vehhab',
      meaning: 'Çok bağışlayan — Karşılıksız sürekli verip bağışlayan',
      value: 14,
      zikirCount: 100,
      fazilet: 'Bolluk ve bereket için okunur',
      nefsMertebesi: 'Radiyye'),
  EsmaEntry(
      arabic: 'الرزاق',
      turkish: 'Er-Rezzak',
      meaning: 'Rızık veren — Tüm varlıklara rızık ulaştıran',
      value: 308,
      zikirCount: 308,
      fazilet: 'Rızık kapılarının açılması için okunur',
      nefsMertebesi: 'Radiyye'),
  EsmaEntry(
      arabic: 'الفتاح',
      turkish: 'El-Fettah',
      meaning: 'Kapıları açan — Her türlü kapalı kapıyı açan',
      value: 489,
      zikirCount: 71,
      fazilet: 'Kapalı kapıların açılması, yeni fırsatlar için',
      nefsMertebesi: 'Mülhime'),
  EsmaEntry(
      arabic: 'العليم',
      turkish: 'El-Alim',
      meaning: 'Her şeyi bilen — Gizli açık her şeyden haberdar',
      value: 150,
      zikirCount: 150,
      fazilet: 'İlim ve hikmeti artırır, hafızayı güçlendirir',
      nefsMertebesi: 'Mülhime'),
  EsmaEntry(
      arabic: 'القابض',
      turkish: 'El-Kabız',
      meaning: 'Daraltan — Dilediğini sıkıştıran, tutan',
      value: 903,
      zikirCount: 100,
      fazilet: 'Aşırılıkları frenlemek için okunur',
      nefsMertebesi: 'Radiyye'),
  EsmaEntry(
      arabic: 'الباسط',
      turkish: 'El-Basit',
      meaning: 'Genişleten — Rızkı ve rahmeti genişleten',
      value: 72,
      zikirCount: 72,
      fazilet: 'Sıkıntı ve darlık zamanlarında okunur',
      nefsMertebesi: 'Radiyye'),
  EsmaEntry(
      arabic: 'الخافض',
      turkish: 'El-Hafid',
      meaning: 'Alçaltan — Zalimleri ve kibir sahiplerini alçaltan',
      value: 1481,
      zikirCount: 100,
      fazilet: 'Kibir ve gururu kırmak için okunur',
      nefsMertebesi: 'Levvame'),
  EsmaEntry(
      arabic: 'الرافع',
      turkish: 'Er-Rafi',
      meaning: 'Yükselten — Değer ve makam yükselten',
      value: 351,
      zikirCount: 100,
      fazilet: 'Makam ve derece için okunur',
      nefsMertebesi: 'Mardiyye'),
  EsmaEntry(
      arabic: 'المعز',
      turkish: 'El-Muizz',
      meaning: 'İzzet veren — İstediğine şeref ve güç veren',
      value: 117,
      zikirCount: 140,
      fazilet: 'İtibar ve saygınlık kazanmak için okunur',
      nefsMertebesi: 'Mardiyye'),
  EsmaEntry(
      arabic: 'المذل',
      turkish: 'El-Müzill',
      meaning: 'Zillete düşüren — Dilediğini alçaltan',
      value: 770,
      zikirCount: 100,
      fazilet: 'Düşmanların zararından korunmak için',
      nefsMertebesi: 'Radiyye'),
  EsmaEntry(
      arabic: 'السميع',
      turkish: 'Es-Semi',
      meaning: 'Her şeyi işiten — Gizli açık tüm sesleri duyan',
      value: 180,
      zikirCount: 100,
      fazilet: 'Duaların kabulü için okumayı artır',
      nefsMertebesi: 'Mülhime'),
  EsmaEntry(
      arabic: 'البصير',
      turkish: 'El-Basir',
      meaning: 'Her şeyi gören — En ince ayrıntıyı bile gören',
      value: 302,
      zikirCount: 100,
      fazilet: 'Basiret ve ileri görüşlülük için okunur',
      nefsMertebesi: 'Mülhime'),
  EsmaEntry(
      arabic: 'الحكم',
      turkish: 'El-Hakem',
      meaning: 'Hükmeden — Mutlak hakim ve karar verici',
      value: 68,
      zikirCount: 68,
      fazilet: 'Adaletli kararlar için, hakemlik gerektiren durumlarda',
      nefsMertebesi: 'Mutmainne'),
  EsmaEntry(
      arabic: 'العدل',
      turkish: 'El-Adl',
      meaning: 'Mutlak adil — Hiç zulmetmeyen',
      value: 104,
      zikirCount: 104,
      fazilet: 'Haksızlığa karşı koruma için okunur',
      nefsMertebesi: 'Mutmainne'),
  EsmaEntry(
      arabic: 'اللطيف',
      turkish: 'El-Latif',
      meaning: 'İnce ve lütufkâr — Gizli sırları bilen, lütuf sahibi',
      value: 129,
      zikirCount: 129,
      fazilet: 'Sıkıntıların kolaylaşması için, letafet için',
      nefsMertebesi: 'Mutmainne'),
  EsmaEntry(
      arabic: 'الخبير',
      turkish: 'El-Habir',
      meaning: 'Her şeyden haberdar — İç ve dış her şeyi bilen',
      value: 812,
      zikirCount: 100,
      fazilet: 'Gizli sırlardan korunmak için okunur',
      nefsMertebesi: 'Mülhime'),
  EsmaEntry(
      arabic: 'الحليم',
      turkish: 'El-Halim',
      meaning: 'Yumuşak huylu — Acele etmeden sabırla davranan',
      value: 88,
      zikirCount: 88,
      fazilet: 'Öfkeyi dindirmek, sabır kazanmak için',
      nefsMertebesi: 'Mutmainne'),
  EsmaEntry(
      arabic: 'العظيم',
      turkish: 'El-Azim',
      meaning: 'Büyüklük sahibi — Sonsuz yücelikte olan',
      value: 1020,
      zikirCount: 100,
      fazilet: 'Büyük işlerin başında, azamet hissi için',
      nefsMertebesi: 'Mutmainne'),
  EsmaEntry(
      arabic: 'الغفور',
      turkish: 'El-Gafur',
      meaning: 'Çok bağışlayan — Günahları örten',
      value: 1286,
      zikirCount: 100,
      fazilet: 'Tövbe dualarına eşlik eder',
      nefsMertebesi: 'Levvame'),
  EsmaEntry(
      arabic: 'الشكور',
      turkish: 'Eş-Şekür',
      meaning: 'Şükrün karşılığını veren — Az amele çok karşılık',
      value: 526,
      zikirCount: 41,
      fazilet: 'Nimetlerin artması için şükürle birlikte okunur',
      nefsMertebesi: 'Radiyye'),
  EsmaEntry(
      arabic: 'العلي',
      turkish: 'El-Ali',
      meaning: 'En yüce — Mutlak yücelikte olan',
      value: 110,
      zikirCount: 110,
      fazilet: 'Yükselmek, makam için okunur',
      nefsMertebesi: 'Mardiyye'),
  EsmaEntry(
      arabic: 'الكبير',
      turkish: 'El-Kebir',
      meaning: 'Büyük — Sonsuz büyüklük sahibi',
      value: 232,
      zikirCount: 100,
      fazilet: 'Tevazuyu hatırlatır, büyüklenmeyi önler',
      nefsMertebesi: 'Levvame'),
  EsmaEntry(
      arabic: 'الحفيظ',
      turkish: 'El-Hafız',
      meaning: 'Her şeyi koruyan — Tüm varlıkları muhafaza eden',
      value: 998,
      zikirCount: 998,
      fazilet: 'Korunma ve hıfz için, hafıza için',
      nefsMertebesi: 'Mülhime'),
  EsmaEntry(
      arabic: 'المقيت',
      turkish: 'El-Mukit',
      meaning: 'Gıda veren — Her varlığa gücü yetecek kadar veren',
      value: 550,
      zikirCount: 100,
      fazilet: 'Sağlık ve güç için okunur',
      nefsMertebesi: 'Radiyye'),
  EsmaEntry(
      arabic: 'الحسيب',
      turkish: 'El-Hasib',
      meaning: 'Hesap gören — Kulların amellerini sayan',
      value: 80,
      zikirCount: 80,
      fazilet: 'Muhasebe ve hesap bilinci için',
      nefsMertebesi: 'Levvame'),
  EsmaEntry(
      arabic: 'الجليل',
      turkish: 'El-Celil',
      meaning: 'Büyüklük ve izzet sahibi — Heybet sahibi',
      value: 73,
      zikirCount: 73,
      fazilet: 'Heybetli duruş ve kabul için okunur',
      nefsMertebesi: 'Mardiyye'),
  EsmaEntry(
      arabic: 'الكريم',
      turkish: 'El-Kerim',
      meaning: 'Çok cömert — Sonsuz ikram sahibi',
      value: 270,
      zikirCount: 270,
      fazilet: 'Cömertlik ve ikram ruhu için',
      nefsMertebesi: 'Mardiyye'),
  EsmaEntry(
      arabic: 'الرقيب',
      turkish: 'Er-Rakib',
      meaning: 'Her şeyi gözeten — Daima ve her yerde gözeten',
      value: 312,
      zikirCount: 312,
      fazilet: 'Gözlem ve denetim için; güvenlik için',
      nefsMertebesi: 'Mutmainne'),
  EsmaEntry(
      arabic: 'المجيب',
      turkish: 'El-Mucib',
      meaning: 'Duaya icabet eden — Her duayı kabul eden',
      value: 55,
      zikirCount: 55,
      fazilet: 'Duaların kabulü için okunur',
      nefsMertebesi: 'Mülhime'),
  EsmaEntry(
      arabic: 'الواسع',
      turkish: 'El-Vasi',
      meaning: 'Geniş — Rahmeti ve ilmi sonsuz geniş olan',
      value: 137,
      zikirCount: 137,
      fazilet: 'Darlığı genişletir, rızık için okunur',
      nefsMertebesi: 'Radiyye'),
  EsmaEntry(
      arabic: 'الحكيم',
      turkish: 'El-Hakim',
      meaning: 'Hikmet sahibi — Her işi hikmetle yapan',
      value: 78,
      zikirCount: 78,
      fazilet: 'Hikmet ve doğru karar için okunur',
      nefsMertebesi: 'Mülhime'),
  EsmaEntry(
      arabic: 'الودود',
      turkish: 'El-Vedud',
      meaning: 'Seven ve sevilen — Sonsuz sevgi sahibi',
      value: 20,
      zikirCount: 33,
      fazilet: 'Kalpler arası sevgiyi artırır',
      nefsMertebesi: 'Mardiyye'),
  EsmaEntry(
      arabic: 'المجيد',
      turkish: 'El-Mecid',
      meaning: 'Şan ve şeref sahibi — Sonsuz iyilik sahibi',
      value: 57,
      zikirCount: 57,
      fazilet: 'Şeref ve izzet için okunur',
      nefsMertebesi: 'Mardiyye'),
  EsmaEntry(
      arabic: 'الباعث',
      turkish: 'El-Bais',
      meaning: 'Dirilten — Ölülerden sonra tekrar dirilten',
      value: 573,
      zikirCount: 100,
      fazilet: 'Ruhsal uyanış için, yeni başlangıçlar için',
      nefsMertebesi: 'Mülhime'),
  EsmaEntry(
      arabic: 'الشهيد',
      turkish: 'Eş-Şehid',
      meaning: 'Her şeye tanık olan — Her yerde ve zamanda hazır',
      value: 319,
      zikirCount: 319,
      fazilet: 'Tanıklık ve şeffaflık için',
      nefsMertebesi: 'Mutmainne'),
  EsmaEntry(
      arabic: 'الحق',
      turkish: 'El-Hakk',
      meaning: 'Mutlak gerçek — Varlığı zorunlu olan tek gerçek',
      value: 108,
      zikirCount: 108,
      fazilet: 'Hakikate ulaşmak, yanlışlıktan korunmak için',
      nefsMertebesi: 'Kâmile'),
  EsmaEntry(
      arabic: 'الوكيل',
      turkish: 'El-Vekil',
      meaning: 'Vekil — İşleri üstlenen, en iyi vekil',
      value: 66,
      zikirCount: 66,
      fazilet: 'Tevekkül için; "Hasbiyallah ve ni\'mel vekil" ile birlikte',
      nefsMertebesi: 'Mutmainne'),
  EsmaEntry(
      arabic: 'القوي',
      turkish: 'El-Kaviyy',
      meaning: 'Güçlü — Sonsuz güç sahibi',
      value: 116,
      zikirCount: 116,
      fazilet: 'Güç ve enerji için okunur',
      nefsMertebesi: 'Emmare'),
  EsmaEntry(
      arabic: 'المتين',
      turkish: 'El-Metin',
      meaning: 'Sağlam — Gücü sonsuz ve değişmez olan',
      value: 500,
      zikirCount: 500,
      fazilet: 'Kararlılık ve sebat için',
      nefsMertebesi: 'Mutmainne'),
  EsmaEntry(
      arabic: 'الولي',
      turkish: 'El-Veliyy',
      meaning: 'Dost — Müminlerin dostu ve yardımcısı',
      value: 46,
      zikirCount: 46,
      fazilet: 'Velayete ulaşmak, Allah\'a yakınlaşmak için',
      nefsMertebesi: 'Mardiyye'),
  EsmaEntry(
      arabic: 'الحميد',
      turkish: 'El-Hamid',
      meaning: 'Her türlü övgüye layık — Hamd yalnız ona',
      value: 62,
      zikirCount: 62,
      fazilet: 'Şükür ve hamd için; nimeti artırır',
      nefsMertebesi: 'Radiyye'),
  EsmaEntry(
      arabic: 'المحصي',
      turkish: 'El-Muhsi',
      meaning: 'Her şeyi sayan — Hiçbir şeyi kaçırmayan',
      value: 148,
      zikirCount: 148,
      fazilet: 'Dikkati artırır, hatalı hesabı düzeltir',
      nefsMertebesi: 'Levvame'),
  EsmaEntry(
      arabic: 'المبدئ',
      turkish: 'El-Mübdi',
      meaning: 'Başlangıç veren — İlk olarak var eden',
      value: 56,
      zikirCount: 56,
      fazilet: 'Yeni başlangıçlar için, ilk adımda',
      nefsMertebesi: 'Mülhime'),
  EsmaEntry(
      arabic: 'المعيد',
      turkish: 'El-Müid',
      meaning: 'Geri döndüren — Yok olanı tekrar var eden',
      value: 124,
      zikirCount: 124,
      fazilet: 'Kaybedilen şeylerin geri dönmesi için',
      nefsMertebesi: 'Radiyye'),
  EsmaEntry(
      arabic: 'المحيي',
      turkish: 'El-Muhyi',
      meaning: 'Dirilten — Hayat veren',
      value: 68,
      zikirCount: 68,
      fazilet: 'Ruhsal ve bedensel güçlenme için',
      nefsMertebesi: 'Mülhime'),
  EsmaEntry(
      arabic: 'المميت',
      turkish: 'El-Mümit',
      meaning: 'Öldüren — Hayatı sona erdiren',
      value: 490,
      zikirCount: 100,
      fazilet: 'Ölüm tefekkürü, dünya bağlarından kurtulmak için',
      nefsMertebesi: 'Mutmainne'),
  EsmaEntry(
      arabic: 'الحي',
      turkish: 'El-Hayy',
      meaning: 'Diri — Ezeli ve ebedi hayat sahibi',
      value: 18,
      zikirCount: 18,
      fazilet: 'Hastalıkta, şifa için; canlılık için',
      nefsMertebesi: 'Mutmainne'),
  EsmaEntry(
      arabic: 'القيوم',
      turkish: 'El-Kayyum',
      meaning: 'Kendi kendine yeten — Her şeyi ayakta tutan',
      value: 156,
      zikirCount: 156,
      fazilet: 'Güçlenme, ayakta durma için',
      nefsMertebesi: 'Kâmile'),
  EsmaEntry(
      arabic: 'الواجد',
      turkish: 'El-Vacid',
      meaning: 'Dilediğini bulan — Her şeye ulaşan',
      value: 14,
      zikirCount: 14,
      fazilet: 'Arayış ve bulma için',
      nefsMertebesi: 'Radiyye'),
  EsmaEntry(
      arabic: 'الماجد',
      turkish: 'El-Macid',
      meaning: 'Şan ve şeref sahibi — Azamet sahibi',
      value: 48,
      zikirCount: 48,
      fazilet: 'Şeref için okunur',
      nefsMertebesi: 'Mardiyye'),
  EsmaEntry(
      arabic: 'الواحد',
      turkish: 'El-Vahid',
      meaning: 'Bir — Zatında, sıfatlarında bir ve tek',
      value: 19,
      zikirCount: 1000,
      fazilet: 'Şirk ve vesveseden kurtulmak için',
      nefsMertebesi: 'Kâmile'),
  EsmaEntry(
      arabic: 'الصمد',
      turkish: 'Es-Samed',
      meaning: 'Her şey ona muhtaç — Hiçbir şeye muhtaç olmayan',
      value: 134,
      zikirCount: 134,
      fazilet: 'Bağımlılıklardan kurtulmak, tam tevekkül için',
      nefsMertebesi: 'Kâmile'),
  EsmaEntry(
      arabic: 'القادر',
      turkish: 'El-Kadir',
      meaning: 'Gücü yeten — Her şeye gücü yeten',
      value: 305,
      zikirCount: 305,
      fazilet: 'Güç ve kudret için, imkânsız görünen işlerde',
      nefsMertebesi: 'Radiyye'),
  EsmaEntry(
      arabic: 'المقتدر',
      turkish: 'El-Muktedir',
      meaning: 'İstediğini yapan — Gücünü dilediğince kullanan',
      value: 744,
      zikirCount: 744,
      fazilet: 'Fiili güç için, eylemlerde başarı için',
      nefsMertebesi: 'Radiyye'),
  EsmaEntry(
      arabic: 'المقدم',
      turkish: 'El-Mukaddim',
      meaning: 'Öne geçiren — Dilediğini öne alan',
      value: 184,
      zikirCount: 184,
      fazilet: 'Öncelik ve öne çıkma için',
      nefsMertebesi: 'Mülhime'),
  EsmaEntry(
      arabic: 'المؤخر',
      turkish: 'El-Muahhir',
      meaning: 'Geri bırakan — Dilediğini geri alan',
      value: 846,
      zikirCount: 846,
      fazilet: 'Tehiri gereken işlerde, sabır için',
      nefsMertebesi: 'Radiyye'),
  EsmaEntry(
      arabic: 'الأول',
      turkish: 'El-Evvel',
      meaning: 'İlk — Önü olmayan',
      value: 37,
      zikirCount: 37,
      fazilet: 'Her işin başında, niyetle birlikte',
      nefsMertebesi: 'Kâmile'),
  EsmaEntry(
      arabic: 'الآخر',
      turkish: 'El-Ahir',
      meaning: 'Son — Sonu olmayan',
      value: 801,
      zikirCount: 801,
      fazilet: 'Son bulmayan, kalıcı işler için',
      nefsMertebesi: 'Kâmile'),
  EsmaEntry(
      arabic: 'الظاهر',
      turkish: 'Ez-Zahir',
      meaning: 'Açık — Her şeyden aşikâr olan',
      value: 1106,
      zikirCount: 1106,
      fazilet: 'Gizli olanı açığa çıkarmak için',
      nefsMertebesi: 'Kâmile'),
  EsmaEntry(
      arabic: 'الباطن',
      turkish: 'El-Batın',
      meaning: 'Gizli — Her şeyin içinde olan',
      value: 62,
      zikirCount: 62,
      fazilet: 'İç dünyayı derinleştirmek için',
      nefsMertebesi: 'Kâmile'),
  EsmaEntry(
      arabic: 'الوالي',
      turkish: 'El-Vali',
      meaning: 'Yöneten — Her şeyi yönetip idare eden',
      value: 47,
      zikirCount: 47,
      fazilet: 'Yöneticilik ve liderlik için',
      nefsMertebesi: 'Mardiyye'),
  EsmaEntry(
      arabic: 'المتعالي',
      turkish: 'El-Müteali',
      meaning: 'Yüce — Sonsuz yücelikte olan',
      value: 551,
      zikirCount: 551,
      fazilet: 'Manevi yükseliş için',
      nefsMertebesi: 'Mardiyye'),
  EsmaEntry(
      arabic: 'البر',
      turkish: 'El-Birr',
      meaning: 'İyilik eden — İyiliği sonsuz olan',
      value: 202,
      zikirCount: 202,
      fazilet: 'İyilik ve bereketli ilişkiler için',
      nefsMertebesi: 'Mardiyye'),
  EsmaEntry(
      arabic: 'التواب',
      turkish: 'Et-Tevvab',
      meaning: 'Tövbeleri kabul eden — Tekrar tekrar dönen',
      value: 409,
      zikirCount: 409,
      fazilet: 'Tövbe için, günahlardan arınma için',
      nefsMertebesi: 'Levvame'),
  EsmaEntry(
      arabic: 'المنتقم',
      turkish: 'El-Müntekim',
      meaning: 'İntikam alan — Suçluları cezalandıran',
      value: 630,
      zikirCount: 100,
      fazilet: 'Zulme uğrayanlara yardım için',
      nefsMertebesi: 'Emmare'),
  EsmaEntry(
      arabic: 'العفو',
      turkish: 'El-Afüvv',
      meaning: 'Affedici — Günahları silen',
      value: 156,
      zikirCount: 156,
      fazilet: 'Af ve bağışlanma için',
      nefsMertebesi: 'Levvame'),
  EsmaEntry(
      arabic: 'الرؤوف',
      turkish: 'Er-Rauf',
      meaning: 'Şefkatli — Merhamet sahibi',
      value: 286,
      zikirCount: 286,
      fazilet: 'Şefkat kazanmak, zorluklarda yumuşama için',
      nefsMertebesi: 'Mutmainne'),
  EsmaEntry(
      arabic: 'مالك الملك',
      turkish: 'Mâlikül Mülk',
      meaning: 'Mülkün gerçek sahibi',
      value: 212,
      zikirCount: 212,
      fazilet: 'Mülk ve mal için',
      nefsMertebesi: 'Radiyye'),
  EsmaEntry(
      arabic: 'ذو الجلال والإكرام',
      turkish: 'Zülcelali vel İkram',
      meaning: 'Celal ve ikram sahibi',
      value: 65,
      zikirCount: 65,
      fazilet: 'Büyüklük ve ikram için',
      nefsMertebesi: 'Kâmile'),
  EsmaEntry(
      arabic: 'المقسط',
      turkish: 'El-Muksit',
      meaning: 'Adaletle davranan',
      value: 209,
      zikirCount: 209,
      fazilet: 'Haksızlığa karşı, adalet için',
      nefsMertebesi: 'Mutmainne'),
  EsmaEntry(
      arabic: 'الجامع',
      turkish: 'El-Cami',
      meaning: 'Toplayan — Dağılanları bir araya getiren',
      value: 114,
      zikirCount: 114,
      fazilet: 'Birlik ve toparlanma için',
      nefsMertebesi: 'Radiyye'),
  EsmaEntry(
      arabic: 'الغني',
      turkish: 'El-Gani',
      meaning: 'Zengin — Hiçbir şeye muhtaç olmayan',
      value: 1060,
      zikirCount: 1060,
      fazilet: 'Fakirlikten kurtulmak için',
      nefsMertebesi: 'Radiyye'),
  EsmaEntry(
      arabic: 'المغني',
      turkish: 'El-Muğni',
      meaning: 'Zenginleştiren — Kullarını zengin kılan',
      value: 1100,
      zikirCount: 1100,
      fazilet: 'Zenginlik ve bereket için',
      nefsMertebesi: 'Radiyye'),
  EsmaEntry(
      arabic: 'المانع',
      turkish: 'El-Mani',
      meaning: 'Engelleyen — Dilediğini önleyen',
      value: 161,
      zikirCount: 161,
      fazilet: 'Kötülüğe engel olmak için',
      nefsMertebesi: 'Mutmainne'),
  EsmaEntry(
      arabic: 'الضار',
      turkish: 'Ed-Darr',
      meaning: 'Zarar veren — Dilediğine zarar veren',
      value: 1001,
      zikirCount: 100,
      fazilet: 'Zarardan korunmak için, tedbir olarak',
      nefsMertebesi: 'Emmare'),
  EsmaEntry(
      arabic: 'النافع',
      turkish: 'En-Nafi',
      meaning: 'Fayda veren — Dilediğine fayda veren',
      value: 201,
      zikirCount: 201,
      fazilet: 'Fayda ve yarar için, hastalıkta',
      nefsMertebesi: 'Radiyye'),
  EsmaEntry(
      arabic: 'النور',
      turkish: 'En-Nur',
      meaning: 'Nur — Alemleri nurlandıran',
      value: 256,
      zikirCount: 256,
      fazilet: 'Kalp nurunu artırmak için; Cuma gecesi okunur',
      nefsMertebesi: 'Mülhime'),
  EsmaEntry(
      arabic: 'الهادي',
      turkish: 'El-Hadi',
      meaning: 'Hidayet veren — Doğru yolu gösteren',
      value: 20,
      zikirCount: 20,
      fazilet: 'Doğru yolda kalmak, karar vermek için',
      nefsMertebesi: 'Mülhime'),
  EsmaEntry(
      arabic: 'البديع',
      turkish: 'El-Bedi',
      meaning: 'Eşsiz yaratan — Benzersiz ve muhteşem yaratan',
      value: 86,
      zikirCount: 86,
      fazilet: 'Yaratıcılık ve estetik için',
      nefsMertebesi: 'Mülhime'),
  EsmaEntry(
      arabic: 'الباقي',
      turkish: 'El-Baki',
      meaning: 'Baki — Sonsuz kalıcı olan',
      value: 113,
      zikirCount: 113,
      fazilet: 'Kalıcılık ve süreklilik için',
      nefsMertebesi: 'Kâmile'),
  EsmaEntry(
      arabic: 'الوارث',
      turkish: 'El-Varis',
      meaning: 'Her şeyin mirasçısı — Her şey ona kalır',
      value: 707,
      zikirCount: 707,
      fazilet: 'Miras ve kalıcılık için',
      nefsMertebesi: 'Kâmile'),
  EsmaEntry(
      arabic: 'الرشيد',
      turkish: 'Er-Reşid',
      meaning: 'Doğru yolu gösteren',
      value: 514,
      zikirCount: 514,
      fazilet: 'İsabetli karar için, rehberlik için',
      nefsMertebesi: 'Mülhime'),
  EsmaEntry(
      arabic: 'الصبور',
      turkish: 'Es-Sabur',
      meaning: 'Çok sabırlı — Acele etmeyen',
      value: 298,
      zikirCount: 298,
      fazilet: 'Sabır için, zor dönemlerde',
      nefsMertebesi: 'Mutmainne'),
  EsmaEntry(
      arabic: 'الشافي',
      turkish: 'Eş-Şafi',
      meaning: 'Şifa veren',
      value: 391,
      zikirCount: 506,
      fazilet: 'Hastalık ve şifa için',
      nefsMertebesi: 'Mutmainne'),
];
